import Link from "next/link";
import { BoxIcon, MusicIcon, SparklesIcon, WandIcon, DownloadIcon, PaletteIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/primitives";
import { PLANS } from "@/lib/plans";

const TILES = [
  { icon: BoxIcon, title: "3D models & characters", text: "Text or image to 3D with PBR textures, auto-rigging and animations. GLB, GLTF, FBX, OBJ.", href: "/app/generate/model_3d" },
  { icon: MusicIcon, title: "Sound", text: "SFX, loopable music and character voices. WAV, OGG, MP3.", href: "/app/generate/audio_sfx" },
];

const FAQ = [
  { q: "What is a credit?", a: "1 credit ≈ $0.01 of provider cost. Every generator shows the exact price before you run it. Subscription credits reset monthly; purchased credits never expire." },
  { q: "Can I use the assets commercially?", a: "The license is part of the Terms of Service, which will be published before launch. Assets are generated by third-party AI models — see the AI Disclosure." },
  { q: "Which engines are supported?", a: "Every asset has Unity, Unreal, Godot and Generic export presets with README instructions in the ZIP." },
  { q: "Do you store my card details?", a: "No. Payments run on Stripe Checkout and the Customer Portal; card data never touches Veyraflow." },
];

export default function LandingPage() {
  return (
    <>
      <section className="mx-auto max-w-6xl px-4 pt-20 pb-16 text-center">
        <div className="bg-primary/10 text-primary mx-auto mb-6 inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-medium">
          <SparklesIcon className="size-3" /> Style-consistent assets per game project
        </div>
        <h1 className="mx-auto max-w-3xl text-4xl font-bold tracking-tight md:text-6xl">Generate game-ready assets with AI</h1>
        <p className="text-muted-foreground mx-auto mt-6 max-w-2xl text-lg">
          Describe what you need. Veyraflow generates 3D models, sound effects, music and voices — and exports them ready to import into Unity, Unreal or Godot.
        </p>
        <div className="mt-8 flex justify-center gap-3">
          <Button asChild size="lg">
            <Link href="/signup">Start generating</Link>
          </Button>
          <Button asChild size="lg" variant="outline">
            <Link href="/pricing">See pricing</Link>
          </Button>
        </div>
      </section>

      <section id="assets" className="mx-auto max-w-6xl px-4 py-12">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {TILES.map((t) => (
            <Card key={t.title} className="hover:border-primary/50 transition-colors">
              <CardHeader>
                <div className="bg-primary/10 text-primary mb-2 inline-flex size-10 items-center justify-center rounded-lg">
                  <t.icon className="size-5" />
                </div>
                <CardTitle>{t.title}</CardTitle>
                <CardDescription>{t.text}</CardDescription>
              </CardHeader>
              <CardContent>
                <Link href={t.href} className="text-primary text-sm underline-offset-4 hover:underline">
                  Try it →
                </Link>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-12">
        <div className="grid items-center gap-8 rounded-2xl border p-8 md:grid-cols-2">
          <div>
            <h2 className="text-2xl font-semibold">Export for Unity, Unreal, Godot</h2>
            <p className="text-muted-foreground mt-3">
              Every asset comes with engine presets: FBX in Unity (Y-up, m) and Unreal (Z-up, cm) variants, GLB/GLTF/OBJ meshes, WAV/OGG/MP3 audio — plus a README with import steps.
            </p>
          </div>
          <div className="grid grid-cols-3 gap-3 text-center text-sm">
            {["Unity", "Unreal", "Godot"].map((e) => (
              <div key={e} className="bg-muted/40 rounded-xl border p-6 font-medium">
                <DownloadIcon className="text-primary mx-auto mb-2 size-5" />
                {e}
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="how" className="mx-auto max-w-6xl px-4 py-12">
        <h2 className="text-center text-2xl font-semibold">How it works</h2>
        <div className="mt-8 grid gap-6 md:grid-cols-3">
          {[
            { icon: PaletteIcon, t: "1. Create a project", d: "Set an art style, perspective, palette and target engine once. Every generation follows it." },
            { icon: WandIcon, t: "2. Describe the asset", d: "Write naturally, in any language. We translate your intent for the specialized model — without adding anything." },
            { icon: DownloadIcon, t: "3. Download for your engine", d: "Pick Unity, Unreal or Godot. Get the right formats, axes, scale and a README." },
          ].map((s) => (
            <div key={s.t} className="rounded-xl border p-6">
              <s.icon className="text-primary mb-3 size-6" />
              <h3 className="font-medium">{s.t}</h3>
              <p className="text-muted-foreground mt-2 text-sm">{s.d}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-12">
        <div className="rounded-2xl border p-8 text-center">
          <h2 className="text-2xl font-semibold">Simple pricing</h2>
          <p className="text-muted-foreground mt-2">
            Try it for ${PLANS.trial.priceUsd} ({PLANS.trial.credits} credits) · Pro ${PLANS.pro.priceUsd}/mo ({PLANS.pro.credits} credits) · Studio ${PLANS.studio.priceUsd}/mo ({PLANS.studio.credits} credits, teams)
          </p>
          <Button asChild className="mt-6">
            <Link href="/pricing">Compare plans</Link>
          </Button>
        </div>
      </section>

      <section className="mx-auto max-w-3xl px-4 py-12">
        <h2 className="text-center text-2xl font-semibold">FAQ</h2>
        <div className="mt-6 divide-y rounded-xl border">
          {FAQ.map((f) => (
            <details key={f.q} className="group p-4">
              <summary className="cursor-pointer list-none font-medium">{f.q}</summary>
              <p className="text-muted-foreground mt-2 text-sm">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 pb-20 text-center">
        <h2 className="text-3xl font-semibold">Ready to build faster?</h2>
        <Button asChild size="lg" className="mt-6">
          <Link href="/signup">Create your account</Link>
        </Button>
      </section>
    </>
  );
}
